name: flutter_structure
description: My Flutter app structure
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_easyloading: ^3.0.5
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  go_router: ^11.1.2
  hydrated_bloc: ^9.1.2
  internet_connection_checker_plus: ^2.0.0
  intl: ^0.18.1
  location: ^5.0.3
  path_provider: ^2.1.1
  weather_repository:
    path: packages/weather_repository
dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.3.3
  http: ^1.1.0
  # mockito: ^5.4.2
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter_assets:
  assets_path: assets/
  output_path: lib/helpers/
  filename: assets.dart

flutter:
  uses-material-design: true
  generate: true
  assets: 
    - assets/
